apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cccxx
  janus-idp.io/tekton: cccxx
  backstage.io/kubernetes-id: cccxx
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cccxx
resources:
- deployment.yaml
- route.yaml
- service.yaml
