apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: cccxx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cccxx 
  name: cccxx
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: cccxx
    weight: 100 
